# Generated by Django 3.0.8 on 2020-07-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the user have verified its email address.', verbose_name='verified'),
        ),
    ]
